// packages/obsidian-plugin/src/ui/svelte/AiQuickAddModal.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { App } from 'obsidian';
  import type { LentaApiClient } from '../../services/lenta-api-client';
  import type { LentaPluginSettings, ParsedNoteCard } from '../../types';
  import { createAiQuickAddStore } from './ai-quick-add-store';

  export let app: App;
  export let apiClient: LentaApiClient;
  export let settings: LentaPluginSettings;
  export let containerId: string | undefined = undefined;
  export let containerName: string | undefined = undefined;
  export let initialFolder: string | undefined = undefined;
  export let initialDate: string | undefined = undefined;
  export let onClose: () => void;
  export let onSuccess: (createdPaths: string[]) => void;

  const store = createAiQuickAddStore();
  const {
    inputText,
    isParsing,
    isSaving,
    errorMessage,
    cards,
    selectedCount,
    totalCount,
    parse,
    toggleCard,
    toggleSelectAll,
    updateCard,
    removeCard,
    addEmptyCard,
    saveSelected,
  } = store;

  // Format today's date for display: DD.MM.YY
  const today = new Date();
  const todayFormatted = `${String(today.getDate()).padStart(2, '0')}.${String(today.getMonth() + 1).padStart(2, '0')}.${String(today.getFullYear()).slice(-2)}`;

  const promptChips = [
    {
      label: '📈 Тренды на сегодня',
      template: `Тренды ${todayFormatted}:\n- Уборка дома\n- Ремонтные работы\n- Warcraft\n- Overwatch`,
    },
    {
      label: '⏳ Тренд-период',
      template: `Тренд: Марафон Гарри Поттера 25.09.26 - 28.09.26 #кино #осень\nПапка: Trends/Cinema`,
    },
    {
      label: '📅 Событие с датой',
      template: `23.09.26 в 19:00 Митап по Svelte и TypeScript в Discord https://discord.gg/lemon #dev\nТег: tech.frontend`,
    },
    {
      label: '✅ Сделано',
      template: `Сделано сегодня: Завершил рефакторинг LentaSidebar и подключил стор. Папка: Projects/Lenta`,
    },
  ];

  function applyChip(template: string) {
    inputText.set(template);
  }

  async function handleParse() {
    const context = {
      defaultDate: initialDate || new Date().toISOString(),
      defaultFolder: initialFolder || 'Trends',
      defaultContainerId: containerId,
      defaultFeedId: 'my-notes',
    };
    await parse(apiClient, context);
  }

  async function handleSave() {
    const result = await saveSelected(app, apiClient, settings, containerId, containerName);
    if (result.success) {
      onSuccess(result.createdPaths);
      onClose();
    }
  }

  function handleTypeChange(tempId: string, event: Event) {
    const target = event.target as HTMLSelectElement;
    const val = target.value;
    if (val === 'Trend') {
      updateCard(tempId, { displayType: 'Trend' });
    } else {
      updateCard(tempId, { type: val as any, displayType: val });
    }
  }
</script>

<div class="ai-quick-add-container">
  <!-- Header -->
  <div class="modal-header">
    <div class="title-row">
      <span class="sparkle-badge">✨ AI ЧАТ</span>
      <h2>Быстрое добавление карточек</h2>
    </div>
    <p class="subtitle">
      Введите произвольный текст, список трендов или события. AI структурирует их в карточки с автоматической датой, фидом и папками.
    </p>
  </div>

  <!-- Prompt Chips -->
  <div class="chips-container">
    <span class="chips-label">Шаблоны:</span>
    {#each promptChips as chip}
      <button
        type="button"
        class="chip-button"
        on:click={() => applyChip(chip.template)}
        disabled={$isParsing || $isSaving}
      >
        {chip.label}
      </button>
    {/each}
  </div>

  <!-- Text Input Area -->
  <div class="input-section">
    <textarea
      class="text-input"
      rows="6"
      placeholder={`Пример:\nТренды ${todayFormatted}:\n- Уборка дома\n- Ремонтные работы\n- Warcraft #игры`}
      bind:value={$inputText}
      disabled={$isParsing || $isSaving}
    ></textarea>

    <div class="parse-action-row">
      <button
        type="button"
        class="parse-button"
        on:click={handleParse}
        disabled={$isParsing || $isSaving || !$inputText.trim()}
      >
        {#if $isParsing}
          <span class="spinner"></span> Распознавание...
        {:else}
          ✨ Сгенерировать карточки
        {/if}
      </button>
    </div>
  </div>

  <!-- Error Message -->
  {#if $errorMessage}
    <div class="error-banner">
      ⚠️ {$errorMessage}
    </div>
  {/if}

  <!-- Cards Preview Section -->
  {#if $cards.length > 0}
    <div class="cards-section">
      <div class="cards-header">
        <div class="selection-controls">
          <label class="select-all-label">
            <input
              type="checkbox"
              checked={$selectedCount === $totalCount && $totalCount > 0}
              on:change={(e) => toggleSelectAll(e.currentTarget.checked)}
            />
            <span>Выбрать все ({$selectedCount} из {$totalCount})</span>
          </label>
        </div>

        <button
          type="button"
          class="add-card-btn"
          on:click={() => addEmptyCard(initialDate, initialFolder)}
        >
          + Добавить карточку
        </button>
      </div>

      <div class="cards-scroll-list">
        {#each $cards as card (card.tempId)}
          <div class="card-item" class:is-selected={card.selected} class:is-trend={card.displayType === 'Trend'}>
            <!-- Checkbox -->
            <div class="card-select">
              <input
                type="checkbox"
                checked={card.selected}
                on:change={() => toggleCard(card.tempId)}
              />
            </div>

            <!-- Card Body -->
            <div class="card-content">
              <!-- Row 1: Type Selector & Title -->
              <div class="card-row title-row">
                <select
                  class="type-select"
                  class:badge-trend={card.displayType === 'Trend'}
                  value={card.displayType === 'Trend' ? 'Trend' : card.type}
                  on:change={(e) => handleTypeChange(card.tempId, e)}
                >
                  <option value="Trend">📈 Trend</option>
                  <option value="SINGLE">📝 Point Note</option>
                  <option value="PERIOD">⏳ Period</option>
                  <option value="EVENT">📅 Event</option>
                  <option value="DONE">✅ Done</option>
                  <option value="FILM_RELEASE">🎬 Release</option>
                </select>

                <input
                  type="text"
                  class="title-input"
                  placeholder="Название карточки"
                  value={card.title}
                  on:input={(e) => updateCard(card.tempId, { title: e.currentTarget.value })}
                />

                <button
                  type="button"
                  class="delete-card-btn"
                  title="Удалить карточку"
                  on:click={() => removeCard(card.tempId)}
                >
                  ✕
                </button>
              </div>

              <!-- Row 2: Dates, Folder, Feed -->
              <div class="card-row meta-row">
                <div class="meta-field">
                  <span class="meta-icon">📅</span>
                  <input
                    type="date"
                    class="date-input"
                    value={card.startDate ? card.startDate.split('T')[0] : ''}
                    on:change={(e) => updateCard(card.tempId, { startDate: e.currentTarget.value })}
                  />
                </div>

                {#if card.type === 'PERIOD' || card.endDate}
                  <div class="meta-field">
                    <span class="meta-label">—</span>
                    <input
                      type="date"
                      class="date-input"
                      value={card.endDate ? card.endDate.split('T')[0] : ''}
                      on:change={(e) => updateCard(card.tempId, { endDate: e.currentTarget.value })}
                    />
                  </div>
                {/if}

                <div class="meta-field flex-1">
                  <span class="meta-icon">📁</span>
                  <input
                    type="text"
                    class="folder-input"
                    placeholder="Папка (Trends, Notes...)"
                    value={card.folder || ''}
                    on:input={(e) => updateCard(card.tempId, { folder: e.currentTarget.value })}
                  />
                </div>

                <div class="meta-field flex-1">
                  <span class="meta-icon">🏷️</span>
                  <input
                    type="text"
                    class="tags-input"
                    placeholder="Хэштеги (#тренд, #игры)"
                    value={(card.hashtags || []).map((h) => `#${h}`).join(' ')}
                    on:input={(e) => {
                      const tags = (e.currentTarget.value.match(/#([\wа-яА-ЯёЁ_-]+)/g) || []).map((h) => h.replace(/^#/, ''));
                      updateCard(card.tempId, { hashtags: tags });
                    }}
                  />
                </div>
              </div>

              <!-- Row 3: Optional Source Link or Taxonomy -->
              {#if card.sourceLink || card.taxonomyPath}
                <div class="card-row extra-row">
                  {#if card.sourceLink}
                    <div class="extra-field">
                      <span class="extra-label">🔗 Ссылка:</span>
                      <a href={card.sourceLink} target="_blank" class="source-link">{card.sourceLink}</a>
                    </div>
                  {/if}
                  {#if card.taxonomyPath}
                    <div class="extra-field">
                      <span class="extra-label">Категория:</span>
                      <span class="tax-badge">{card.taxonomyPath}</span>
                    </div>
                  {/if}
                </div>
              {/if}
            </div>
          </div>
        {/each}
      </div>
    </div>
  {/if}

  <!-- Footer Actions -->
  <div class="modal-footer">
    <button type="button" class="btn-cancel" on:click={onClose} disabled={$isSaving}>
      Отмена
    </button>

    <button
      type="button"
      class="btn-save"
      on:click={handleSave}
      disabled={$isSaving || $selectedCount === 0}
    >
      {#if $isSaving}
        <span class="spinner"></span> Сохранение...
      {:else}
        ✨ Добавить выбранные ({$selectedCount})
      {/if}
    </button>
  </div>
</div>

<style>
  .ai-quick-add-container {
    display: flex;
    flex-direction: column;
    gap: 16px;
    padding: 8px 4px;
    max-height: 82vh;
    box-sizing: border-box;
  }

  .modal-header h2 {
    margin: 4px 0 2px 0;
    font-size: 1.35rem;
    font-weight: 700;
  }

  .title-row {
    display: flex;
    align-items: center;
    gap: 10px;
  }

  .sparkle-badge {
    background: linear-gradient(135deg, #a855f7 0%, #ec4899 100%);
    color: #ffffff;
    font-size: 0.72rem;
    font-weight: 700;
    padding: 2px 8px;
    border-radius: 12px;
    letter-spacing: 0.5px;
    text-transform: uppercase;
  }

  .subtitle {
    margin: 0;
    font-size: 0.85rem;
    color: var(--text-muted);
    line-height: 1.4;
  }

  .chips-container {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 6px;
  }

  .chips-label {
    font-size: 0.8rem;
    color: var(--text-muted);
    font-weight: 600;
  }

  .chip-button {
    background: var(--background-secondary);
    border: 1px solid var(--background-modifier-border);
    border-radius: 14px;
    font-size: 0.78rem;
    padding: 3px 10px;
    cursor: pointer;
    color: var(--text-normal);
    transition: all 0.15s ease;
  }

  .chip-button:hover:not(:disabled) {
    border-color: var(--interactive-accent);
    color: var(--interactive-accent);
    background: var(--background-secondary-alt);
  }

  .input-section {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .text-input {
    width: 100%;
    background: var(--background-primary);
    border: 1px solid var(--background-modifier-border);
    border-radius: 8px;
    padding: 10px 12px;
    font-family: inherit;
    font-size: 0.9rem;
    color: var(--text-normal);
    resize: vertical;
    box-sizing: border-box;
    transition: border-color 0.2s;
  }

  .text-input:focus {
    outline: none;
    border-color: var(--interactive-accent);
    box-shadow: 0 0 0 2px rgba(168, 85, 247, 0.2);
  }

  .parse-action-row {
    display: flex;
    justify-content: flex-end;
  }

  .parse-button {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    background: linear-gradient(135deg, #8b5cf6 0%, #d946ef 100%);
    color: white;
    font-weight: 600;
    padding: 8px 18px;
    border-radius: 8px;
    border: none;
    cursor: pointer;
    font-size: 0.88rem;
    transition: transform 0.15s, opacity 0.15s;
  }

  .parse-button:hover:not(:disabled) {
    transform: translateY(-1px);
    opacity: 0.95;
  }

  .parse-button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .error-banner {
    background: rgba(239, 68, 68, 0.15);
    border: 1px solid rgba(239, 68, 68, 0.3);
    color: #ef4444;
    padding: 8px 12px;
    border-radius: 6px;
    font-size: 0.85rem;
  }

  .cards-section {
    display: flex;
    flex-direction: column;
    gap: 8px;
    margin-top: 4px;
  }

  .cards-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 4px 2px;
  }

  .select-all-label {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 0.85rem;
    font-weight: 600;
    cursor: pointer;
  }

  .add-card-btn {
    background: none;
    border: 1px dashed var(--background-modifier-border);
    color: var(--text-muted);
    border-radius: 6px;
    padding: 3px 10px;
    font-size: 0.8rem;
    cursor: pointer;
  }

  .add-card-btn:hover {
    color: var(--text-normal);
    border-color: var(--text-muted);
  }

  .cards-scroll-list {
    display: flex;
    flex-direction: column;
    gap: 10px;
    max-height: 42vh;
    overflow-y: auto;
    padding-right: 4px;
  }

  .card-item {
    display: flex;
    align-items: flex-start;
    gap: 10px;
    background: var(--background-secondary);
    border: 1px solid var(--background-modifier-border);
    border-radius: 8px;
    padding: 10px 12px;
    transition: border-color 0.15s, background-color 0.15s;
  }

  .card-item.is-selected {
    border-color: rgba(168, 85, 247, 0.4);
    background: var(--background-secondary-alt);
  }

  .card-item.is-trend {
    border-left: 3px solid #a855f7;
  }

  .card-select {
    padding-top: 4px;
  }

  .card-content {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .card-row {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
  }

  .type-select {
    font-size: 0.78rem;
    font-weight: 600;
    padding: 4px 8px;
    border-radius: 6px;
    background: var(--background-primary);
    border: 1px solid var(--background-modifier-border);
    color: var(--text-normal);
    cursor: pointer;
  }

  .badge-trend {
    color: #c084fc;
    border-color: #a855f7;
  }

  .title-input {
    flex: 1;
    font-weight: 600;
    font-size: 0.95rem;
    background: var(--background-primary);
    border: 1px solid var(--background-modifier-border);
    border-radius: 6px;
    padding: 4px 8px;
    color: var(--text-normal);
  }

  .title-input:focus {
    outline: none;
    border-color: var(--interactive-accent);
  }

  .delete-card-btn {
    background: none;
    border: none;
    color: var(--text-muted);
    font-size: 0.9rem;
    cursor: pointer;
    padding: 4px 8px;
    border-radius: 4px;
  }

  .delete-card-btn:hover {
    color: #ef4444;
    background: rgba(239, 68, 68, 0.1);
  }

  .meta-row {
    font-size: 0.8rem;
  }

  .meta-field {
    display: flex;
    align-items: center;
    gap: 4px;
    background: var(--background-primary);
    border: 1px solid var(--background-modifier-border);
    border-radius: 6px;
    padding: 2px 6px;
  }

  .meta-icon {
    font-size: 0.8rem;
  }

  .date-input,
  .folder-input,
  .tags-input {
    background: transparent;
    border: none;
    font-size: 0.8rem;
    color: var(--text-normal);
    outline: none;
    width: 100%;
  }

  .flex-1 {
    flex: 1;
    min-width: 120px;
  }

  .extra-row {
    font-size: 0.78rem;
    color: var(--text-muted);
  }

  .source-link {
    color: var(--text-accent);
    text-decoration: none;
    max-width: 300px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .tax-badge {
    background: rgba(59, 130, 246, 0.15);
    color: #60a5fa;
    padding: 1px 6px;
    border-radius: 4px;
  }

  .modal-footer {
    display: flex;
    justify-content: flex-end;
    align-items: center;
    gap: 10px;
    margin-top: 8px;
    padding-top: 12px;
    border-top: 1px solid var(--background-modifier-border);
  }

  .btn-cancel {
    background: var(--background-secondary);
    border: 1px solid var(--background-modifier-border);
    color: var(--text-muted);
    padding: 7px 16px;
    border-radius: 6px;
    cursor: pointer;
  }

  .btn-cancel:hover {
    color: var(--text-normal);
  }

  .btn-save {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    background: var(--interactive-accent);
    color: var(--text-on-accent);
    font-weight: 600;
    padding: 7px 18px;
    border-radius: 6px;
    border: none;
    cursor: pointer;
    transition: opacity 0.15s;
  }

  .btn-save:hover:not(:disabled) {
    opacity: 0.9;
  }

  .btn-save:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .spinner {
    display: inline-block;
    width: 12px;
    height: 12px;
    border: 2px solid rgba(255, 255, 255, 0.3);
    border-radius: 50%;
    border-top-color: white;
    animation: spin 0.6s linear infinite;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
</style>

// apps/calendar-app/src/components/AiQuickAddModal.tsx
import React, { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import {
  Sparkles,
  X,
  Check,
  Calendar,
  Folder,
  Tag,
  Trash2,
  Plus,
  Loader2,
  TrendingUp,
  Clock,
  CheckCircle,
  FileText,
  Film,
} from 'lucide-react';
import { ParsedNoteCard, NoteType, CreateNoteInput } from '@lenta/shared';
import { calendarApi } from '../api/client';

interface AiQuickAddModalProps {
  isOpen: boolean;
  onClose: () => void;
  defaultDate?: string;
  defaultFolder?: string;
}

export const AiQuickAddModal: React.FC<AiQuickAddModalProps> = ({
  isOpen,
  onClose,
  defaultDate,
  defaultFolder,
}) => {
  const queryClient = useQueryClient();

  const today = new Date();
  const todayFormatted = `${String(today.getDate()).padStart(2, '0')}.${String(today.getMonth() + 1).padStart(2, '0')}.${String(today.getFullYear()).slice(-2)}`;

  const promptChips = [
    {
      label: '📈 Тренды на сегодня',
      template: `Тренды ${todayFormatted}:\n- Уборка дома\n- Ремонтные работы\n- Warcraft\n- Overwatch`,
    },
    {
      label: '⏳ Тренд-период',
      template: `Тренд: Марафон Гарри Поттера 25.09.26 - 28.09.26 #кино #осень\nПапка: Trends/Cinema`,
    },
    {
      label: '📅 Событие с датой',
      template: `23.09.26 в 19:00 Митап по Svelte и TypeScript в Discord https://discord.gg/lemon #dev\nТег: tech.frontend`,
    },
    {
      label: '✅ Сделано',
      template: `Сделано сегодня: Завершил рефакторинг LentaSidebar и подключил стор. Папка: Projects/Lenta`,
    },
  ];

  const [inputText, setInputText] = useState('');
  const [isParsing, setIsParsing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [cards, setCards] = useState<ParsedNoteCard[]>([]);

  if (!isOpen) return null;

  const selectedCards = cards.filter((c) => c.selected);
  const selectedCount = selectedCards.length;
  const allSelected = cards.length > 0 && selectedCount === cards.length;

  const handleParse = async () => {
    if (!inputText.trim()) {
      setErrorMessage('Пожалуйста, введите текст для разбора.');
      return;
    }

    setIsParsing(true);
    setErrorMessage(null);

    try {
      const res = await calendarApi.parseAiNotes(inputText.trim(), {
        defaultDate: defaultDate || new Date().toISOString(),
        defaultFolder: defaultFolder || 'Trends',
        defaultFeedId: 'my-notes',
      });

      const parsedCards = res.cards || [];
      if (parsedCards.length === 0) {
        setErrorMessage('Не удалось выделить карточки. Попробуйте другой формат или список.');
      } else {
        setCards(parsedCards.map((c, i) => ({ ...c, selected: true, tempId: c.tempId || `card-${i + 1}` })));
      }
    } catch (err: any) {
      setErrorMessage(`Ошибка распознавания: ${err?.message || err}`);
    } finally {
      setIsParsing(false);
    }
  };

  const toggleCard = (tempId: string) => {
    setCards((prev) =>
      prev.map((c) => (c.tempId === tempId ? { ...c, selected: !c.selected } : c))
    );
  };

  const toggleSelectAll = (select: boolean) => {
    setCards((prev) => prev.map((c) => ({ ...c, selected: select })));
  };

  const updateCard = (tempId: string, patch: Partial<ParsedNoteCard>) => {
    setCards((prev) =>
      prev.map((c) => {
        if (c.tempId !== tempId) return c;
        const updated = { ...c, ...patch };
        if (patch.displayType === 'Trend') {
          updated.type = updated.endDate ? 'PERIOD' : 'SINGLE';
          if (!updated.hashtags) updated.hashtags = [];
          if (!updated.hashtags.includes('тренд')) updated.hashtags.unshift('тренд');
        }
        return updated;
      })
    );
  };

  const removeCard = (tempId: string) => {
    setCards((prev) => prev.filter((c) => c.tempId !== tempId));
  };

  const addEmptyCard = () => {
    const newCard: ParsedNoteCard = {
      tempId: `manual-${Date.now()}`,
      title: 'Новый тренд',
      type: 'SINGLE',
      displayType: 'Trend',
      startDate: defaultDate || new Date().toISOString(),
      endDate: null,
      feedSlug: 'my-notes',
      feedTitle: 'My Notes',
      folder: defaultFolder || 'Trends',
      hashtags: ['тренд'],
      icon: 'trending-up',
      description: '',
      selected: true,
    };
    setCards((prev) => [...prev, newCard]);
  };

  const handleSave = async () => {
    if (selectedCards.length === 0) return;

    setIsSaving(true);
    setErrorMessage(null);

    try {
      const payload: CreateNoteInput[] = selectedCards.map((c) => ({
        title: c.title.trim(),
        type: c.type as NoteType,
        startDate: c.startDate.includes('T') ? c.startDate : new Date(`${c.startDate}T12:00:00.000Z`).toISOString(),
        endDate: c.endDate ? (c.endDate.includes('T') ? c.endDate : new Date(`${c.endDate}T23:59:59.000Z`).toISOString()) : undefined,
        folder: c.folder || 'Notes',
        folders: c.folder ? [c.folder] : undefined,
        hashtags: c.hashtags,
        tagIds: c.taxonomyPath ? [c.taxonomyPath] : c.tagIds,
        sourceLink: c.sourceLink,
        icon: c.icon,
        description: c.description,
      }));

      await calendarApi.createNotesBatch(payload);

      // Invalidate queries so timeline, month view, and calendar refresh
      await queryClient.invalidateQueries({ queryKey: ['notes'] });
      await queryClient.invalidateQueries({ queryKey: ['folders'] });
      await queryClient.invalidateQueries({ queryKey: ['hashtags'] });

      onClose();
    } catch (err: any) {
      setErrorMessage(`Ошибка сохранения карточек: ${err?.message || err}`);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-2xl max-h-[90vh] flex flex-col bg-[#161818] border border-[#2b2e2e] rounded-xl shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#242828] bg-gradient-to-r from-purple-950/20 via-pink-950/10 to-transparent">
          <div className="flex items-center gap-3">
            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-bold font-mono tracking-wider bg-purple-500/20 text-purple-300 border border-purple-500/30">
              <Sparkles className="w-3.5 h-3.5 text-purple-400" />
              AI ЧАТ
            </span>
            <h2 className="text-base font-semibold text-[#f1f1f1] font-sans">
              Быстрое добавление карточек
            </h2>
          </div>

          <button
            onClick={onClose}
            className="p-1 rounded-lg text-[#93927e] hover:text-[#f1f1f1] hover:bg-[#242828] transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          <p className="text-xs text-[#a0a090] font-sans">
            Введите текст на естественном языке (тренды, события, задачи, периоды). AI автоматически преобразует текст в структурированные карточки.
          </p>

          {/* Prompt Chips */}
          <div className="flex items-center flex-wrap gap-2 pt-1">
            <span className="text-[11px] font-mono text-[#808070] font-semibold">Шаблоны:</span>
            {promptChips.map((chip, idx) => (
              <button
                key={idx}
                type="button"
                onClick={() => setInputText(chip.template)}
                disabled={isParsing || isSaving}
                className="px-2.5 py-1 rounded-full text-xs font-mono bg-[#1e2020] border border-[#2e3232] text-[#c9c7b2] hover:border-purple-500 hover:text-purple-300 hover:bg-purple-950/20 transition-all cursor-pointer"
              >
                {chip.label}
              </button>
            ))}
          </div>

          {/* Text Area */}
          <div className="space-y-2">
            <textarea
              rows={5}
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              disabled={isParsing || isSaving}
              placeholder={`Пример:\nТренды ${todayFormatted}:\n- Уборка дома\n- Ремонтные работы\n- Warcraft #игры`}
              className="w-full bg-[#101212] border border-[#2b2e2e] focus:border-purple-500 focus:ring-1 focus:ring-purple-500 rounded-lg p-3 text-xs font-mono text-[#e2e2e2] placeholder-[#606050] outline-none transition-all resize-y"
            />

            <div className="flex justify-end">
              <button
                type="button"
                onClick={handleParse}
                disabled={isParsing || isSaving || !inputText.trim()}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg font-sans font-semibold text-xs text-white bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 disabled:opacity-50 disabled:cursor-not-allowed shadow-md transition-all cursor-pointer"
              >
                {isParsing ? (
                  <>
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    <span>Распознавание...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>Распознать карточки</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Error Banner */}
          {errorMessage && (
            <div className="p-3 bg-red-950/30 border border-red-800/40 rounded-lg text-xs text-red-300">
              ⚠️ {errorMessage}
            </div>
          )}

          {/* Cards Section */}
          {cards.length > 0 && (
            <div className="space-y-3 pt-2">
              <div className="flex items-center justify-between text-xs text-[#a0a090] border-b border-[#242828] pb-2">
                <label className="flex items-center gap-2 font-medium cursor-pointer">
                  <input
                    type="checkbox"
                    checked={allSelected}
                    onChange={(e) => toggleSelectAll(e.target.checked)}
                    className="rounded border-[#3a3e3e] bg-[#121414] text-purple-600 focus:ring-purple-500"
                  />
                  <span>Выбрать все ({selectedCount} из {cards.length})</span>
                </label>

                <button
                  type="button"
                  onClick={addEmptyCard}
                  className="flex items-center gap-1 text-[11px] font-mono text-[#8b5cf6] hover:text-purple-300 transition-colors"
                >
                  <Plus className="w-3 h-3" />
                  <span>Добавить карточку</span>
                </button>
              </div>

              {/* Cards List */}
              <div className="space-y-2.5 max-h-60 overflow-y-auto pr-1">
                {cards.map((card) => {
                  const isTrend = card.displayType === 'Trend';
                  return (
                    <div
                      key={card.tempId}
                      className={`flex items-start gap-3 p-3 rounded-lg border transition-all ${
                        card.selected
                          ? 'bg-[#1b1d1d] border-purple-900/40'
                          : 'bg-[#141515] border-[#242828] opacity-60'
                      } ${isTrend ? 'border-l-4 border-l-purple-500' : ''}`}
                    >
                      {/* Checkbox */}
                      <div className="pt-1">
                        <input
                          type="checkbox"
                          checked={card.selected}
                          onChange={() => toggleCard(card.tempId)}
                          className="rounded border-[#3a3e3e] bg-[#121414] text-purple-600 focus:ring-purple-500"
                        />
                      </div>

                      {/* Content */}
                      <div className="flex-1 space-y-2">
                        {/* Title & Type */}
                        <div className="flex items-center gap-2">
                          <select
                            value={card.displayType === 'Trend' ? 'Trend' : card.type}
                            onChange={(e) => {
                              const val = e.target.value;
                              if (val === 'Trend') {
                                updateCard(card.tempId, { displayType: 'Trend' });
                              } else {
                                updateCard(card.tempId, { type: val as any, displayType: val });
                              }
                            }}
                            className={`text-[11px] font-mono font-semibold py-1 px-2 rounded border bg-[#121414] ${
                              isTrend
                                ? 'border-purple-600/50 text-purple-300'
                                : 'border-[#3a3e3e] text-[#c9c7b2]'
                            }`}
                          >
                            <option value="Trend">📈 Trend</option>
                            <option value="SINGLE">📝 Point Note</option>
                            <option value="PERIOD">⏳ Period</option>
                            <option value="EVENT">📅 Event</option>
                            <option value="DONE">✅ Done</option>
                            <option value="FILM_RELEASE">🎬 Release</option>
                          </select>

                          <input
                            type="text"
                            value={card.title}
                            placeholder="Название карточки"
                            onChange={(e) => updateCard(card.tempId, { title: e.target.value })}
                            className="flex-1 bg-[#121414] border border-[#2b2e2e] focus:border-purple-500 rounded py-1 px-2.5 text-xs text-[#f1f1f1] font-sans font-medium outline-none"
                          />

                          <button
                            type="button"
                            onClick={() => removeCard(card.tempId)}
                            className="p-1 rounded text-[#707060] hover:text-red-400 hover:bg-red-950/20 transition-colors"
                            title="Удалить"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>

                        {/* Dates & Folder & Tags */}
                        <div className="flex items-center flex-wrap gap-2 text-[11px] font-mono text-[#a0a090]">
                          <div className="flex items-center gap-1 bg-[#121414] border border-[#2b2e2e] rounded px-2 py-0.5">
                            <Calendar className="w-3 h-3 text-[#808070]" />
                            <input
                              type="date"
                              value={card.startDate ? card.startDate.split('T')[0] : ''}
                              onChange={(e) => updateCard(card.tempId, { startDate: e.target.value })}
                              className="bg-transparent border-none text-[#c9c7b2] outline-none text-[11px]"
                            />
                          </div>

                          {(card.type === 'PERIOD' || card.endDate) && (
                            <div className="flex items-center gap-1 bg-[#121414] border border-[#2b2e2e] rounded px-2 py-0.5">
                              <span className="text-[#808070]">—</span>
                              <input
                                type="date"
                                value={card.endDate ? card.endDate.split('T')[0] : ''}
                                onChange={(e) => updateCard(card.tempId, { endDate: e.target.value })}
                                className="bg-transparent border-none text-[#c9c7b2] outline-none text-[11px]"
                              />
                            </div>
                          )}

                          <div className="flex items-center gap-1 bg-[#121414] border border-[#2b2e2e] rounded px-2 py-0.5">
                            <Folder className="w-3 h-3 text-[#808070]" />
                            <input
                              type="text"
                              value={card.folder || ''}
                              placeholder="Папка"
                              onChange={(e) => updateCard(card.tempId, { folder: e.target.value })}
                              className="bg-transparent border-none text-[#c9c7b2] outline-none text-[11px] w-24"
                            />
                          </div>

                          <div className="flex items-center gap-1 bg-[#121414] border border-[#2b2e2e] rounded px-2 py-0.5 flex-1 min-w-[120px]">
                            <Tag className="w-3 h-3 text-[#808070]" />
                            <input
                              type="text"
                              value={(card.hashtags || []).map((h) => `#${h}`).join(' ')}
                              placeholder="#хэштеги"
                              onChange={(e) => {
                                const tags = (e.target.value.match(/#([\wа-яА-ЯёЁ_-]+)/g) || []).map((h) => h.replace(/^#/, ''));
                                updateCard(card.tempId, { hashtags: tags });
                              }}
                              className="bg-transparent border-none text-[#c9c7b2] outline-none text-[11px] w-full"
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-[#242828] bg-[#121414]">
          <button
            type="button"
            onClick={onClose}
            disabled={isSaving}
            className="px-4 py-2 rounded-lg font-sans text-xs text-[#a0a090] hover:text-[#f1f1f1] hover:bg-[#1e2020] transition-colors"
          >
            Отмена
          </button>

          <button
            type="button"
            onClick={handleSave}
            disabled={isSaving || selectedCount === 0}
            className="inline-flex items-center gap-2 px-5 py-2 rounded-lg font-sans font-semibold text-xs text-[#121414] bg-[#c9cd58] hover:bg-[#dce06b] disabled:opacity-50 disabled:cursor-not-allowed shadow-md transition-all cursor-pointer"
          >
            {isSaving ? (
              <>
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                <span>Сохранение...</span>
              </>
            ) : (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Добавить выбранные ({selectedCount})</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
